version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: stockin_postgres
    environment:
      POSTGRES_DB: stockin_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - stockin-network

  app:
    build: .
    container_name: stockin_app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/stockin_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8080:8080"
    networks:
      - stockin-network

volumes:
  postgres_data:

networks:
  stockin-network:
